### PR TITLE
to display only device name

### PR DESCRIPTION
**Pull request by dadaa**
Hello,
The reason of this pull request is that some devices may not be able to use "Firefox OS" brand.
Could you consider this?

### CODE REVIEW

**Comment by jryans** [comment]
Is there any additional data from `getprop` or other shell commands that can be used to identify "not Firefox OS" devices?

Many of the model names for existing phones are inscrutable strings like "LD1231", so for Firefox OS branded devices, it helps to include those words as it does currently.

**Comment by autonome** [comment]
Most devices that developers are using will not be branded Firefox OS - eg, our Flames and Z3Cs.

B2G is likely to be more often correct if you absolutely must use a general-case string there.

**Comment by jryans** [comment]
Actually, I just checked my Z3C, and it already includes (B2G) in the name, so you end up with Firefox OS (Xperia Z3 Compact (B2G)).

Okay, I think I am convinced. Let's move forward with this. Thanks for the change!

**Comment by jryans** [comment]
@dadaa, do you need a new version of the add-on to be released with this change?

**Comment by dadaa** [comment]
@jryans Thank you very much!
Yes, I want to use that!

**Comment by jryans** [comment]
@dadaa Okay, I've released 0.8.7 with this change. It may take up to 24 hours before the update appears in Firefox.

**Comment by dadaa** [comment]
@jryans Thank you! I could confirm the change!

**Pull request merged**
